SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE UPDATE_UTILITY(
    PI_UTILITY_NAME UTILITY.UTILITY_NAME%TYPE,
    PI_LEASE_ID UTILITY.LEASE_LEASE_ID%TYPE,
    PI_UNITS_ADD UTILITY.CURR_CYCLE_UNITS%TYPE
    )
AS  
    v_billing_id NUMBER := 0;
    v_last_date DATE := SYSDATE;
    v_unit_cost NUMBER :=0;
    v_cur_units NUMBER :=0;
BEGIN   
    
    SELECT UTILITY_BILLING_ID INTO v_billing_id 
    FROM UTILITY 
    WHERE 
    LEASE_LEASE_ID = PI_LEASE_ID
    AND 
    UTILITY_NAME = PI_UTILITY_NAME;

    SELECT CYCLE_BILLED_ON INTO v_last_date
    FROM UTILITY
    WHERE UTILITY_BILLING_ID = v_billing_id;
    
    SELECT CURR_CYCLE_UNITS INTO v_cur_units
    FROM UTILITY
    WHERE UTILITY_BILLING_ID = v_billing_id;   
    
    SELECT utility_cost INTO v_unit_cost
    FROM UTILITY
    WHERE UTILITY_BILLING_ID = v_billing_id;
    
    IF SYSDATE > v_last_date THEN 
        UPDATE LEASE 
        SET PENDING_DUES = NVL(PENDING_DUES,0) + (v_unit_cost*v_cur_units)
        WHERE lease_id = PI_LEASE_ID;
        DBMS_OUTPUT.PUT_LINE('UPDATING PENDING DUES BY: ' || TO_CHAR(v_unit_cost*v_cur_units));
        COMMIT;
        
        UPDATE UTILITY
        SET CURR_CYCLE_UNITS = PI_UNITS_ADD,
        CYCLE_BILLED_ON = LAST_DAY(SYSDATE)
        WHERE UTILITY_BILLING_ID = v_billing_id;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('SET CURR_CYCLE_UNITS TO 0');
    ELSE 
        UPDATE UTILITY
        SET CURR_CYCLE_UNITS = CURR_CYCLE_UNITS + PI_UNITS_ADD
        WHERE UTILITY_BILLING_ID = v_billing_id;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('ADDED UNITS');
    END IF;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO PREVIOUS RECORDS FOUND. INSERTING VALUES');
    IF PI_UTILITY_NAME = 'ELECTRICITY' THEN
    INSERT INTO UTILITY VALUES (UTILITY_ID_SEQ.NEXTVAL, PI_UTILITY_NAME, 100.00, 'KWH',PI_UNITS_ADD, LAST_DAY(SYSDATE), PI_LEASE_ID);
    ELSIF PI_UTILITY_NAME = 'ELECTRICITY' THEN
    INSERT INTO UTILITY VALUES (UTILITY_ID_SEQ.NEXTVAL, PI_UTILITY_NAME, 5.00 , 'GALLON',PI_UNITS_ADD, LAST_DAY(SYSDATE), PI_LEASE_ID);
    ELSIF PI_UTILITY_NAME = 'ELECTRICITY' THEN
    INSERT INTO UTILITY VALUES (UTILITY_ID_SEQ.NEXTVAL, PI_UTILITY_NAME, 8.00, 'KG',PI_UNITS_ADD, LAST_DAY(SYSDATE), PI_LEASE_ID);
    END IF;
END UPDATE_UTILITY;
/

--works
--EXEC UPDATE_UTILITY('ELECTRICITY',50,2);