CREATE OR REPLACE PROCEDURE ONBOARD_RESIDENT(
    PI_RESIDENT_NAME RESIDENT.RESIDENT_NAME%TYPE,
    PI_PHONE_NO NUMBER,
    PI_NATIONALITY RESIDENT.NATIONALITY%TYPE,
    PI_GENDER RESIDENT.GENDER%TYPE,
    PI_DOB RESIDENT.DOB%TYPE,
    PI_SSN RESIDENT.SSN%TYPE,
    PI_LEASE_ID NUMBER
)
AS
    v_lease_check NUMBER := 1;
    v_ssn_check VARCHAR2(9) := 'xxxxxxxxx';  -- Corrected variable name
    E_INVALID_LEASE EXCEPTION;
BEGIN
    -- Check for lease
    SELECT lease_id INTO v_lease_check
    FROM LEASE
    WHERE lease_id = PI_LEASE_ID;

    -- Check for SSN
    BEGIN 
        SELECT ssn INTO v_ssn_check
        FROM RESIDENT
        WHERE ssn = PI_SSN;

        DBMS_OUTPUT.PUT_LINE('PLEASE ENTER A UNIQUE SSN');

    EXCEPTION
        WHEN NO_DATA_FOUND THEN    
            -- Insert the resident if either lease or SSN is not found
            INSERT INTO RESIDENT (
                RESIDENT_ID, RESIDENT_NAME, PHONE_NO, NATIONALITY, GENDER, DOB, SSN, LEASE_LEASE_ID
            ) VALUES (
                RESIDENT_ID_SEQ.NEXTVAL, PI_RESIDENT_NAME, PI_PHONE_NO, PI_NATIONALITY,
                PI_GENDER, PI_DOB, PI_SSN, PI_LEASE_ID
            );
            COMMIT;
    END;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('PLEASE ENTER A VALID LEASE ID');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END ONBOARD_RESIDENT;
/
