SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE CANCEL_AMENITY(
    PI_BOOKING_ID AMENITY_BOOKING.BOOKING_ID%TYPE,
    PI_LEASE_ID AMENITY_BOOKING.LEASE_LEASE_ID%TYPE
    )
AS
    v_check_booking NUMBER :=0;
    v_booking_start DATE := SYSDATE ; 
    v_booking_end DATE := SYSDATE;
    v_actual_lease NUMBER := 0;
    v_total_cost NUMBER := 0;
    v_amenity_id NUMBER := 0;
    E_INVALID_COMBO EXCEPTION;
    E_OLD_BOOKING EXCEPTION;
BEGIN
    SELECT BOOKING_ID INTO v_check_booking
    FROM AMENITY_BOOKING
    WHERE BOOKING_ID = PI_BOOKING_ID;
    
    SELECT LEASE_LEASE_ID INTO v_actual_lease
    FROM AMENITY_BOOKING
    WHERE BOOKING_ID = PI_BOOKING_ID;
    
    IF PI_LEASE_ID != v_actual_lease THEN
    RAISE E_INVALID_COMBO;
    END IF;
    
    SELECT AMENITY_AMENITY_ID INTO v_amenity_id
    FROM AMENITY_BOOKING
    WHERE BOOKING_ID = PI_BOOKING_ID;
    
    SELECT BOOKING_FROM INTO v_booking_start
    FROM AMENITY_BOOKING 
    WHERE BOOKING_ID = PI_BOOKING_ID;
    
    SELECT BOOKING_TO INTO v_booking_end
    FROM AMENITY_BOOKING 
    WHERE BOOKING_ID = PI_BOOKING_ID;
    
    IF v_booking_start < (SYSDATE + INTERVAL '30' MINUTE) THEN 
    RAISE E_OLD_BOOKING;
    END IF;
    
    SELECT HOURLY_CHARGE * ((v_booking_end - v_booking_start)*24) INTO v_total_cost 
    FROM AMENITIES
    WHERE amenity_id = v_amenity_id;
        
    UPDATE AMENITY_BOOKING
    SET CANCELLATION_STATUS = 'cancelled'
    WHERE BOOKING_ID = PI_BOOKING_ID;
    DBMS_OUTPUT.PUT_LINE('BOOKING HAS BEEN CANCELLED FOR BOOKING_ID: ' || TO_CHAR(PI_BOOKING_ID));
    UPDATE LEASE 
    SET PENDING_DUES = NVL(PENDING_DUES,0) - v_total_cost
    WHERE lease_id = PI_LEASE_ID;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('AMENITY CHARGE OF ' || TO_CHAR(v_total_cost) || ' HAS BEEN DEDUCTED FROM THE PENDING DUES IN YOUR LEASE');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('BOOKING/LEASE COMBO DOES NOT EXIST');
    WHEN E_INVALID_COMBO THEN
    DBMS_OUTPUT.PUT_LINE('BOOKING/LEASE COMBO DOES NOT EXIST');
    WHEN E_OLD_BOOKING THEN
    DBMS_OUTPUT.PUT_LINE('CANCELLATION IS ALLOWED ONLY IF MORE THAN 30 MINUTES BEFORE SCHEDULED START TIME');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
END CANCEL_AMENITY;
/

EXEC BOOK_AMENITY(5,'parking',1, SYSDATE+10 ,SYSDATE+10.5);
-- WRONG BOOKING_ID
--EXEC CANCEL_AMENITY(1000,5);
-- WRONG LEASE_ID
--EXEC CANCEL_AMENITY(22,1000);
-- BAD TIME 
--EXEC CANCEL_AMENITY(1,1);
--PROPER
--EXEC CANCEL_AMENITY(29,5);
