CREATE OR REPLACE PROCEDURE ADD_VIOLATION(
    PI_LEASE_ID VIOLATIONS.LEASE_LEASE_ID%TYPE,
    PI_PENALTY NUMBER,
    PI_TYPE VARCHAR2
)
AS
BEGIN
    INSERT INTO VIOLATIONS (
        VIOLATION_ID, LEASE_LEASE_ID, PENALTY, TYPE
    ) VALUES (
        violation_id_seq.NEXTVAL, PI_LEASE_ID, PI_PENALTY, PI_TYPE
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END ADD_VIOLATION;
/
EXEC ADD_VIOLATION('1', 500, 'Pet');

select * from violations where lease_lease_id=1;
