CREATE OR REPLACE PROCEDURE ONBOARD_OWNER(
    PI_OWNER_NAME OWNER.OWNER_NAME%TYPE,
    PI_PHONE_NO OWNER.PHONE_NO%TYPE,
    PI_NATIONALITY OWNER.NATIONALITY%TYPE,
    PI_GENDER OWNER.GENDER%TYPE,
    PI_DOB OWNER.DOB%TYPE,
    PI_SSN OWNER.SSN%TYPE
)
AS
    v_ssn_check VARCHAR2(9) := 'xxxxxxxxx';  -- Placeholder for SSN check
    E_SSN_ALREADY_EXISTS EXCEPTION;
BEGIN
    -- Check for SSN
    BEGIN 
        SELECT ssn INTO v_ssn_check
        FROM OWNER
        WHERE ssn = PI_SSN;

        RAISE E_SSN_ALREADY_EXISTS;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN    
            -- Insert the owner if SSN is not found
            INSERT INTO OWNER (
                OWNER_ID, OWNER_NAME, PHONE_NO, NATIONALITY, GENDER, DOB, SSN
            ) VALUES (
                OWNER_ID_SEQ.NEXTVAL, PI_OWNER_NAME, PI_PHONE_NO, PI_NATIONALITY,
                PI_GENDER, PI_DOB, PI_SSN
            );
            COMMIT;
    END;

EXCEPTION
    WHEN E_SSN_ALREADY_EXISTS THEN
        DBMS_OUTPUT.PUT_LINE('PLEASE ENTER A UNIQUE SSN');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END ONBOARD_OWNER;
/

EXECUTE ONBOARD_OWNER('Test', 1234567890, 'American', 'Male', TO_DATE('1990-01-01', 'YYYY-MM-DD'), '123456789');


SELECT * FROM OWNER WHERE SSN = '123456789';




