-- RESIDENT GRANTS 
GRANT SELECT ON IT_ADMIN.BOOKINGS_VIEW TO RESIDENT_ROLE;
GRANT SELECT ON IT_ADMIN.RESIDENT_UTILITY_USAGE TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.BOOK_AMENITY TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.CANCEL_AMENITY TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.UPDATE_UTILITY TO RESIDENT_ROLE;

-- LEASING OFFICE GRANTS
GRANT SELECT ON IT_ADMIN.office_view_amenities TO LEASING_OFFICE;
GRANT EXECUTE ON IT_ADMIN.CLOSE_AMENITY TO LEASING_OFFICE;


-- MAINTAINENCE GRANTS
