-- RESIDENT GRANTS 
GRANT SELECT ON IT_ADMIN.BOOKINGS_VIEW TO RESIDENT_ROLE;
GRANT SELECT ON IT_ADMIN.RESIDENT_UTILITY_USAGE TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.BOOK_AMENITY TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.CANCEL_AMENITY TO RESIDENT_ROLE;
GRANT EXECUTE ON IT_ADMIN.UPDATE_UTILITY TO RESIDENT_ROLE;
GRANT SELECT ON IT_ADMIN.RESIDENT_SR TO RESIDENT_ROLE;

-- LEASING OFFICE GRANTS
GRANT SELECT ON IT_ADMIN.office_view_amenities TO LEASING_OFFICE_ROLE;
GRANT EXECUTE ON IT_ADMIN.CLOSE_AMENITY TO LEASING_OFFICE_ROLE;

-- MAINTAINENCE GRANTS
GRANT EXECUTE ON IT_ADMIN.add_sr TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.onboard_employee TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.onboard_department TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.close_sr TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.schedule_emp TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.fire_emp TO MAINTENANCE_ROLE;
GRANT EXECUTE ON IT_ADMIN.before_sr_insert TO MAINTENANCE_ROLE;
GRANT SELECT, UPDATE ON IT_ADMIN.SERVICE_REQUEST_ID_SEQ TO MAINTENANCE_ROLE;
GRANT SELECT, UPDATE ON IT_ADMIN.EMPLOYEE_ID_SEQ TO MAINTENANCE_ROLE;
GRANT SELECT ON IT_ADMIN.ASSIGNMENTS TO MAINTENANCE_ROLE;
