CREATE OR REPLACE PROCEDURE fire_emp(
    p_emp_id IN NUMBER, 
    p_name IN VARCHAR2
) AS
    V_EXISTS VARCHAR2(1) := 'N';
    V_NAME VARCHAR2(50);
    V_DEPT_ID NUMBER;
    V_NEW_EMPLOYEE_NAME VARCHAR2(50);

BEGIN
    SELECT 'Y', EMPLOYEE_NAME, DEPARTMENT_DEPT_ID
    INTO V_EXISTS, V_NAME, V_DEPT_ID
    FROM EMPLOYEE 
    WHERE EMPLOYEE_ID = p_emp_id AND EMPLOYEE_NAME = INITCAP(p_name);

    IF V_EXISTS = 'Y' THEN
        SELECT EMPLOYEE_NAME
        INTO V_NEW_EMPLOYEE_NAME
        FROM EMPLOYEE
        WHERE DEPARTMENT_DEPT_ID = V_DEPT_ID
          AND EMPLOYEE_ID != p_emp_id
        ORDER BY DBMS_RANDOM.VALUE
        FETCH FIRST 1 ROW ONLY;
        DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID = p_emp_id;
        DBMS_OUTPUT.PUT_LINE('Sorry ' || V_NAME || '! Goodbye :(');
        UPDATE SERVICE_REQUEST
        SET STATUS = 'Assigned to ' || V_NEW_EMPLOYEE_NAME
        WHERE STATUS = 'Assigned to ' || V_NAME
        AND TYPE IN (SELECT NAME FROM DEPARTMENT WHERE DEPT_ID = V_DEPT_ID);

        DBMS_OUTPUT.PUT_LINE('If any current SRs exists then ' || V_NEW_EMPLOYEE_NAME || ' will take care after employee departure.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Employee not found.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE('Oops!'||SUBSTR(SQLERRM, 11));
END fire_emp;
/
